package es.cic.tessa.model.mappers;


import java.util.List;
import java.util.stream.Collectors;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Component;
import es.cic.tessa.model.Asset;
import es.cic.tessa.model.HistoricalAsset;


@Component
public class HistoricalAssetToEntityMapper
{

    @Lazy
    @Autowired
    private HistoricalTemplateToEntityMapper historicalTemplateToEntityMapper;

    @Lazy
    @Autowired
    private HistoricalAssetValueToEntityMapper historicalAssetValueToEntityMapper;

    @Lazy
    @Autowired
    private HistoricalOrganizerToEntityMapper historicalOrganizerToEntityMapper;


    public Asset historicalAssetToAsset(HistoricalAsset historicalAsset)
    {

	if(historicalAsset == null)
	{
	    return null;
	}

	Asset asset = new Asset();

	// Campos compartidos via TessaElement/IdentificableElement/LockableElement/DateTimeElement
	asset.setCustomId(historicalAsset.getCustomId());
	asset.setId(historicalAsset.getId());
	asset.setName(historicalAsset.getName());
	asset.setNameLower(historicalAsset.getNameLower());
	asset.setDescription(historicalAsset.getDescription());
	asset.setNemonic(historicalAsset.getNemonic());
	asset.setGroups(historicalAsset.getGroups());
	asset.setIcon(historicalAsset.getIcon());
	asset.setVersion(historicalAsset.getVersion());
	asset.setInsertDate(historicalAsset.getInsertDate());
	asset.setModifDate(historicalAsset.getModifDate());

	// Campos propios de Asset
	asset.setIdentificator(historicalAsset.getIdentificator());
	asset.setIdentificatorLower(historicalAsset.getIdentificator() != null ? historicalAsset.getIdentificator().toLowerCase() : null);
	asset.setActive(historicalAsset.getActive());
	asset.setPhysicalPath(historicalAsset.getPhysicalPath());
	asset.setLogicalPath(historicalAsset.getLogicalPath());
	asset.setNumComplexAssets(historicalAsset.getNumComplexAssets());

	// Campos que la entidad viva tiene y el snapshot no
	asset.setHistoricalAsset(null);
	asset.setAutoGeneratedEnabled(null);

	// Relaciones anidadas
	asset.setTemplate(historicalTemplateToEntityMapper.historicalTemplateToTemplate(historicalAsset.getHistoricalTemplate()));
	asset.setDependsAsset(historicalAssetToAsset(historicalAsset.getHistoricalDependsAsset()));

	if(historicalAsset.getHistoricalValues() != null)
	{
	    asset.setValues(historicalAssetValueToEntityMapper.historicalAssetValueListToAssetValueList(historicalAsset.getHistoricalValues()));
	}

	if(historicalAsset.getHistoricalOrganizers() != null)
	{
	    asset.setOrganizers(historicalOrganizerToEntityMapper.historicalOrganizerListToOrganizerList(historicalAsset.getHistoricalOrganizers()));
	}

	// historicalChange: sin destino en la entidad viva, se ignora

	return asset;
    }


    public List<Asset> historicalAssetListToAssetList(List<HistoricalAsset> historicalAssets)
    {

	if(historicalAssets == null)
	{
	    return List.of();
	}

	return historicalAssets.stream()
		.map(this::historicalAssetToAsset)
		.collect(Collectors.toList());
    }

}
