/*
 * Copyright [2019] "CIC Consulting"
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
 *
 */
package es.cic.tessa.model;


import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import org.springframework.data.annotation.Transient;
import org.springframework.data.neo4j.core.schema.GeneratedValue;
import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Property;
import org.springframework.data.neo4j.core.schema.Relationship;
import org.springframework.data.neo4j.core.schema.Relationship.Direction;
import org.springframework.lang.Nullable;
import es.cic.tessa.common.model.Labels;
import es.cic.tessa.common.model.Relations;
import es.cic.tessa.model.support.TessaElement;


@Node(Labels.ASSET)
public class Asset extends TessaElement implements Comparable<Asset>
{

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue
    protected Long nodeId;

    @Property(name = "identificator")
    protected String identificator;

    @Property(name = "identificatorLower")
    protected String identificatorLower;

    @Property(name = "active")
    protected Boolean active = Boolean.TRUE;

    @Property(name = "physicalPath")
    protected String physicalPath;

    @Property(name = "logicalPath")
    protected List<String> logicalPath;

    @Relationship(type = Relations.DEFINED_BY_RELATION, direction = Direction.OUTGOING)
    private Template template;

    @Relationship(type = Relations.DEPENDS_RELATION, direction = Direction.OUTGOING)
    private Asset dependsAsset;

    @Relationship(type = Relations.HAS_VALUE_RELATION, direction = Direction.OUTGOING)
    private Collection<AssetValue> values = new LinkedList<>();

    @Relationship(type = Relations.HISTORICAL_CHANGE_RELATION, direction = Direction.OUTGOING)
    private Collection<HistoricalChange> historicalChanges = new LinkedHashSet<>();

    @Relationship(type = Relations.CONTAINED_RELATION, direction = Direction.OUTGOING)
    private Collection<Organizer> organizers = new LinkedList<>();

    @Property(name = "historicalAsset")
    protected Boolean historicalAsset = Boolean.FALSE;

    @Property(name = "autoGeneratedEnabled")
    @Nullable
    private Boolean autoGeneratedEnabled;

    @Transient
    private Integer numComplexAssets = Integer.valueOf(0);

    public Asset()
    {

    }


    public Asset(String identificator, Template template, Set<String> groups)
    {

	super(identificator, groups);
	this.identificator = identificator;
	this.identificatorLower = identificator.toLowerCase();
	nameLower = identificator.toLowerCase();
	this.template = template;
    }


    @Override
    public Long getId()
    {

	return nodeId;
    }


    @Override
    public void setId(Long nodeId)
    {

	this.nodeId = nodeId;
    }


    public Template getTemplate()
    {

	return template;
    }


    public void setTemplate(Template template)
    {

	this.template = template;
    }


    public Asset getDependsAsset()
    {

	return dependsAsset;
    }


    public void setDependsAsset(Asset dependsAsset)
    {

	this.dependsAsset = dependsAsset;
    }


    public Collection<HistoricalChange> getHistoricalChanges()
    {

	return historicalChanges;
    }


    public void setHistoricalChanges(Set<HistoricalChange> historicalChanges)
    {

	this.historicalChanges = historicalChanges;
    }


    public Collection<Organizer> getOrganizers()
    {

	return organizers;
    }


    public void setOrganizers(List<Organizer> organizers)
    {

	this.organizers = organizers;
    }


    public void addOrganizer(Organizer organizer)
    {

	getOrganizers().add(organizer);

    }


    public void addOrganizers(List<Organizer> organizers)
    {

	getOrganizers().addAll(organizers);

    }


    public Integer getNumComplexAssets()
    {

	return numComplexAssets;
    }


    public void setNumComplexAssets(Integer numComplexAssets)
    {

	this.numComplexAssets = numComplexAssets;
    }


    public void addValue(AssetValue value)
    {

	values.add(value);
    }


    public void addValues(List<AssetValue> assetAttributeValues)
    {

	values.addAll(assetAttributeValues);
    }


    public Collection<AssetValue> getValues()
    {

	return values;
    }


    public void setValues(List<AssetValue> values)
    {

	this.values = values;
    }


    public String getIdentificator()
    {

	return identificator;
    }


    public void setIdentificator(String identificator)
    {

	this.identificator = identificator;
    }


    public String getIdentificatorLower()
    {

	return identificatorLower;
    }


    public void setIdentificatorLower(String identificatorLower)
    {

	this.identificatorLower = identificatorLower;
    }


    public Boolean getHistoricalAsset()
    {

	return historicalAsset;
    }


    public void setHistoricalAsset(Boolean historicalAsset)
    {

	this.historicalAsset = historicalAsset;
    }


    public Boolean getAutoGeneratedEnabled()
    {

	return autoGeneratedEnabled;
    }


    public void setAutoGeneratedEnabled(Boolean autoGeneratedEnabled)
    {

	this.autoGeneratedEnabled = autoGeneratedEnabled;
    }


    public String getPhysicalPath()
    {

	return physicalPath;
    }


    public void setPhysicalPath(String physicalPath)
    {

	this.physicalPath = physicalPath;
    }


    public List<String> getLogicalPath()
    {

	return logicalPath;
    }


    public void setLogicalPath(List<String> logicalPath)
    {

	this.logicalPath = logicalPath;
    }


    public Boolean getActive()
    {

	return active;
    }


    public void setActive(Boolean active)
    {

	this.active = active;
    }


    @Override
    public int compareTo(Asset o)
    {

	if(this.getNemonic() == null && o.getNemonic() == null)
	{
	    return 0;
	}
	if(this.getNemonic() == null)
	{
	    return -1;
	}
	if(o.getNemonic() == null)
	{
	    return 1;
	}
	return this.getNemonic().compareTo(o.getNemonic());

    }


    @Override
    public String toString()
    {

	return "Asset [id=" + getCustomId() + ", identificator=" + identificator + " , name=" + name + ", template=" + (template != null ? template.getName() : "null") + ", groups=" + groups + "]";
    }

}
